# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: https://jecastro1.github.io/
baseurl: https://jecastro1.github.io/
title: Jaime Castro
author: Jaime Castro
description: Personal blog and resume
avatar: profile.jpg
email: jecastro1@uc.cl
github: jecastro1 # username
twitter: sirjaimecastro
linkedin: jecastro1
# stackoverflow: username   #e.g: users/2735833/proton1h1
# Comment out if you don't want disqus 
# disqus: username
# google_analytics: UA-69391421-1


# needed for travis-ci build
exclude: [vendor]
